duraark-metadata:
  image: duraark/duraark-metadata:0.7.0
  ports:
    - "5012:5012"
#  If you are also using the 'duraark-sessions' service use 'volumes_from'
#  instead of 'volumes' to link to the file storage.
#  volumes-from:
#    - duraark-sessions
  volumes:
    - /tmp/duraark:/duraark-storage
